name: Release Current Version

on:
  push:
    tags:
      - v*

env:
  KBT_VERSION: 27.0.78
  RUNNER_HOME: /home/runner
  KBT_ARCHIVE: /home/runner/xp-kbt.tar.gz
  KBT_DIR: /home/runner/xp-kbt
  TEMP_DIR: /home/runner/temp/eXtractionAndProcessing/output/packages

jobs:
  release_pipeline:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar
  
    - name: Download xp-kbt archive
      run: |
        KBT_URL="https://github.com/vxcontrol/xp-kbt/releases/download/${{ env.KBT_VERSION }}/kbt.${{ env.KBT_VERSION }}-linux.tar.gz"
        wget $KBT_URL -O ${{ env.KBT_ARCHIVE }}
  
    - name: Extract xp-kbt archive
      run: |
        mkdir -p ${{ env.KBT_DIR }}
        tar -xzvf ${{ env.KBT_ARCHIVE }} -C ${{ env.KBT_DIR }}

    - name: Package Full
      run: |
        mkdir -p ${{ env.TEMP_DIR }}
        dotnet ${{ env.KBT_DIR }}/extra-tools/kbpack/kbpack.dll pack -s $GITHUB_WORKSPACE -o ${{ env.TEMP_DIR }}/pack.full.current.kb

    - name: Package Open
      run: |
        chmod +x ./.github/scripts/filter_open_content.sh
        ./.github/scripts/filter_open_content.sh $GITHUB_WORKSPACE
        rm -r ${{ env.TEMP_DIR }}
        mkdir -p ${{ env.TEMP_DIR }}
        dotnet ${{ env.KBT_DIR }}/extra-tools/kbpack/kbpack.dll pack -s $GITHUB_WORKSPACE -o ${{ env.TEMP_DIR }}/pack.open.current.kb

    - name: Check packaged files
      run: |
        ls -l ${{ env.TEMP_DIR }}
        test -f ${{ env.TEMP_DIR }}/pack.full.current.kb || (echo "pack.full.current.kb not found" && exit 1)
        test -f ${{ env.TEMP_DIR }}/pack.open.current.kb || (echo "pack.open.current.kb not found" && exit 1)
  
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ env.TEMP_DIR }}/pack.full.current.kb
          ${{ env.TEMP_DIR }}/pack.open.current.kb
        draft: false
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  