name: Release Current Version

on:
  workflow_dispatch:

env:
  KBT_VERSION: 27.0.78
  RUNNER_HOME: /home/runner
  KBT_ARCHIVE: /home/runner/xp-kbt.tar.gz
  KBT_DIR: /home/runner/xp-kbt
  TEMP_DIR: /home/runner/temp/eXtractionAndProcessing/output/packages

jobs:
  release_pipeline:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar
  
    - name: Download xp-kbt archive
      run: |
        KBT_URL="https://github.com/vxcontrol/xp-kbt/releases/download/${{ env.KBT_VERSION }}/kbt.${{ env.KBT_VERSION }}-linux.tar.gz"
        wget $KBT_URL -O ${{ env.KBT_ARCHIVE }}
  
    - name: Extract xp-kbt archive
      run: |
        mkdir -p ${{ env.KBT_DIR }}
        tar -xzvf ${{ env.KBT_ARCHIVE }} -C ${{ env.KBT_DIR }}

    - name: Package Full - Current Version
      run: |
        mkdir -p ${{ env.TEMP_DIR }}
        dotnet /home/runner/xp-kbt/extra-tools/kbpack/kbpack.dll pack -s $GITHUB_WORKSPACE -o /home/runner/temp/eXtractionAndProcessing/output/packages/pack.full.current.kb

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: packages-full
        path: /home/runner/temp/eXtractionAndProcessing/output/packages/

    - name: Package Open - Current Version
      run: |
        chmod +x ./.github/scripts/filter_open_content.sh /home/runner/work/open-xp-rules-test/open-xp-rules-test
        dotnet /home/runner/xp-kbt/extra-tools/kbpack/kbpack.dll pack -s $GITHUB_WORKSPACE -o /home/runner/temp/eXtractionAndProcessing/output/packages/pack.open.current.kb

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: packages-open
        path: /home/runner/temp/eXtractionAndProcessing/output/packages/

