name: Tests

on:
  workflow_dispatch:

env:
  KBT_VERSION: "27.0.78"
  KBT_URL: "https://github.com/vxcontrol/xp-kbt/releases/download/${KBT_VERSION}/kbt.${KBT_VERSION}-linux.tar.gz"

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update package list
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar

    - name: Download xp-kbt archive
      run: |
        wget $KBT_URL -O /home/runner/xp-kbt.tar.gz

    - name: Extract xp-kbt archive
      run: |
        mkdir -p /home/runner/xp-kbt
        tar -xzvf /home/runner/xp-kbt.tar.gz -C /home/runner/xp-kbt

    - name: Run tests
      run: |
        mkdir -p /home/runner/temp/eXtractionAndProcessing/output/packages
        /home/runner/xp-kbt/extra-tools/siemj/siemj -c .github/config/siemj.conf main